### ISSUE TITLE
Font problem

### ISSUE THREAD

**Issue by hfkhfdsf** [wp3sixty/woo-custom-emails#11]
Great plugin!

I have everything in the template, in the Arial font, but the following will NOT change to Arial:
{email_order_items_table}
{email_addresses}
It looks like Times new roman is used.

How can I make it so?

**Comment by hfkhfdsf** [comment]
I found: <tr><th scope='row' colspan='2'
		 style='font-family: arial;text-align:left; border: 1px solid #eee; <?php echo 1 == $i ? 'border-top-width: 2px;' : ''; ?>'><?php echo $total['label']; ?></th>
					<td style='font-family:arial;text-align:right; border: 1px solid #eee; <?php echo 1 == $i ? 'border-top-width: 2px;' : ''; ?>'><?php echo $total['value']; ?></td>
					</tr><?php

in the class WCEmails_Instance.php and there I've changed that font, so the {email_order_total_footer} has the Arial font now.
How can I change this for the: {email_order_items_table} and the {email_addresses}?

**Comment by PatelUtkarsh** [comment]
I don't see any such issue check this ![screen](https://drive.google.com/uc?export=view&id=0B0DqzoHJhsGvb2ZmNGFVd2FnUEU) 

Can you please update the version and check again if you're running a older version?

**Comment by hfkhfdsf** [comment]
Hello,

 

I have te newest version: 2.0.4…

I made a image for you so you can see the problem.

I added a font-family line to the existing style info in the class-wcemails-instance.php.

Can we do the same for the class-wcemails-instance.php and the {email_order_total_footer}?

 

I hope you can help

 

Greetings Ilona

 

 

Van: Utkarsh Patel [mailto:notifications@github.com] 
Verzonden: zaterdag 16 januari 2016 7:39
Aan: mehulkaklotar/woo-custom-emails
CC: hfkhfdsf
Onderwerp: Re: [woo-custom-emails] Font problem (#11)

 

I don't see any such issue check this  <https://camo.githubusercontent.com/9033db4d2e0e7bb1673df341f0eec15e41f23fc6/68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f6578706f72743d766965772669643d30423044717a6f484a6873477662325a6d4e4746566432466e554555> 

Can you please update the version and check again if you're running a older version?

**Comment by PatelUtkarsh** [comment]
I can not find image can please share the image?

**Comment by hfkhfdsf** [comment]
Hello,

 

Look at:

http://nl.tinypic.com/view.php?pic=14lugso <http://nl.tinypic.com/view.php?pic=14lugso&s=9#.Vp4bIvnhDcs> &s=9#.Vp4bIvnhDcs

 

Greetings Ilona

 

Van: Utkarsh Patel [mailto:notifications@github.com] 
Verzonden: maandag 18 januari 2016 17:24
Aan: mehulkaklotar/woo-custom-emails
CC: hfkhfdsf
Onderwerp: Re: [woo-custom-emails] Font problem (#11)

 

I can not find image can please share the image?

**Comment by mehulkaklotar** [comment]
Hello @hfkhfdsf,

I think we can just make the template available for you to style it according to your choice. It is being generated by php in backend right now. We will release the fix asap once we get the template on front end.

Thanks for pointing out the issue.

**Comment by mehulkaklotar** [comment]
Hi @hfkhfdsf,

You can change the font style by overriding the woocommerce email template:

Go to `woocommerce > templates > emails > email-order-items.php` and copy this file in to `{your theme} > woocommerce > templates > emails > email-order-items.php`  and change the style according to your requirement. By doing so, you can change the font of product row or can change the entire layout/content.

**Comment by hfkhfdsf** [comment]
Hello,

 

Your info does not work.

De problem is still there…

 

Greetings Ilona

 

Van: Mehul Kaklotar [mailto:notifications@github.com] 
Verzonden: dinsdag 19 januari 2016 16:04
Aan: mehulkaklotar/woo-custom-emails
CC: hfkhfdsf
Onderwerp: Re: [woo-custom-emails] Font problem (#11)

 

Hi @hfkhfdsf <https://github.com/hfkhfdsf> ,

You can change the font style by overriding the woocommerce email template:

Go to woocommerce > templates > emails > email-order-items.php and copy this file in to {your theme} > woocommerce > templates > emails > email-order-items.php and change the style according to your requirement. By doing so, you can change the font of product row or can change the entire layout/content.

**Comment by mehulkaklotar** [comment]
Sorry @hfkhfdsf ,

There is a problem in path I gave you.
Go to `woocommerce > templates > emails > email-order-items.php` and copy this file in to `{your theme} > woocommerce > emails > email-order-items.php` and change the style according to your requirement.

**Comment by hfkhfdsf** [comment]
Nope still not working.

The file is in the attachment of this email…

What am I doing wrong?

 

Van: Mehul Kaklotar [mailto:notifications@github.com] 
Verzonden: donderdag 21 januari 2016 7:35
Aan: wp3sixty/woo-custom-emails
CC: hfkhfdsf
Onderwerp: Re: [woo-custom-emails] Font problem (#11)

 

Sorry @hfkhfdsf <https://github.com/hfkhfdsf>  ,

There is a problem in path I gave you.
Go to woocommerce > templates > emails > email-order-items.php and copy this file in to {your theme} > woocommerce > emails > email-order-items.php and change the style according to your requirement.

**Comment by mehulkaklotar** [comment]
@hfkhfdsf I can't find the attachment here.

**Comment by hfkhfdsf** [comment]
Why don’t you see my attachments?

Anyway…

I’ve send you the file with wetranser

Download-link 
 <http://we.tl/MI23bTk9p9> http://we.tl/MI23bTk9p9

 

Hope to hear from you soon

 

 

Van: Mehul Kaklotar [mailto:notifications@github.com] 
Verzonden: vrijdag 22 januari 2016 7:17
Aan: wp3sixty/woo-custom-emails
CC: hfkhfdsf
Onderwerp: Re: [woo-custom-emails] Font problem (#11)

 

@hfkhfdsf <https://github.com/hfkhfdsf>  I can't find the attachment here.

**Comment by mehulkaklotar** [comment]
@hfkhfdsf can you see the style you have added in email markup?

**Comment by hfkhfdsf** [comment]
I’m sorry, I don’t understand what you mean…

Can you help me please?

 

 

Van: Mehul Kaklotar [mailto:notifications@github.com] 
Verzonden: dinsdag 26 januari 2016 10:27
Aan: wp3sixty/woo-custom-emails
CC: hfkhfdsf
Onderwerp: Re: [woo-custom-emails] Font problem (#11)

 

@hfkhfdsf <https://github.com/hfkhfdsf>  can you see the style you have added in email markup?

**Comment by mehulkaklotar** [comment]
@hfkhfdsf can you send me the screenshot of actual email sent with html view of email. so that i can see if style is applied or not?

**Comment by hfkhfdsf** [comment]
See:

http://oi66.tinypic.com/72vk89.jpg

 

I’ll send you the email to.

 

 

Van: Mehul Kaklotar [mailto:notifications@github.com] 
Verzonden: dinsdag 26 januari 2016 21:13
Aan: wp3sixty/woo-custom-emails
CC: hfkhfdsf
Onderwerp: Re: [woo-custom-emails] Font problem (#11)

 

@hfkhfdsf <https://github.com/hfkhfdsf>  can you send me the screenshot of actual email sent with html view of email. so that i can see if style is applied or not?

**Comment by hfkhfdsf** [comment]
Van: De geboortekaartwinkel [mailto:il.willemsen@gmail.com] 
Verzonden: woensdag 27 januari 2016 14:06
Aan: il.willemsen@live.nl
Onderwerp: Betaling ontvangen

 


 

  <http://www.u1275p488.web0082.zxcs.nl/wp-content/themes/WCM010013-child-cosmetic/images/logo.png> 

 <http://www.u1275p488.web0082.zxcs.nl/klantenservice/> Klantenservice  <http://www.u1275p488.web0082.zxcs.nl/klantenservice/account/verlanglijstje/> Verlanglijstje  <http://www.u1275p488.web0082.zxcs.nl/mijn-account/> Mijn account 


Betaling ontvangen


We hebben je betaling ontvangen, bedankt!
Je hebt het kaartje ook al goed gekeurd, dus nu is het wachten tot de geboorte.


 


  _____  


BESTELLING


  _____  


 

 

 


Bestelnummer: 4240

 

 Besteldatum: 14 januari 2016


 

 

 


Product

Aantal

Prijs

	

Kaart 1

1 

€ 1,00 

	

Subtotaal:

€ 1,00


Verzending:

€ 6,50 via PostNL 


Betaalmethode:

Vooruitbetaling per Bank/Giro (gratis)


Totaal:

€ 7,50 (Inclusief € 1,30 BTW)


 


CONTACTGEGEVENS:


  _____  


E-email:  <mailto:il.willemsen@live.nl> il.willemsen@live.nl

 

 


Tel: 543543535

 

 


 

 

 



Factuuradres:

fgdgdg fgddg
dfgdgd 56
5645EF gdfgdfg

Bezorgadres:

dfgdfg gfdgdg
dfg 45
5465EF fgdfgd

 

Vragen, opmerkingen of suggesties?
Stuur je bericht via webchat, WhatsApp of Facebook!

support@
0123-456789
 <http://www.degeboortekaartwinkel.nl> www.degeboortekaartwinkel.nl
 <http://www.facebook.nl/> www.facebook.nl/

 <http://www.u1275p488.web0082.zxcs.nl/klantenservice/> Klantenservice  <http://www.u1275p488.web0082.zxcs.nl/klantenservice/account/verlanglijstje/> Verlanglijstje  <http://www.u1275p488.web0082.zxcs.nl/mijn-account/> Mijn account

**Comment by mehulkaklotar** [comment]
It looks like the style you have given, is being parsed or filtered by woocommerce email parser.

You can try `<style>` tag and write your own css for the email template. Include it in email template in custom email settings section.
