### ISSUE TITLE
email tags

### ISSUE THREAD

**Issue by hleong** [wp3sixty/woo-custom-emails#12]
Hello,

There are currently a limited number of preset tags that we can use in the email. How can I create more of my own pulling fields from woocommerce email template (e.g. product's thumb image and product title with hyperlink (upon clicking which it can directed to product page) and SKU, quantity, unit price, total etc)?

Thanks very much in advance

**Comment by mehulkaklotar** [comment]
@hleong,

You can change or override the woocommerce default templates into your theme for the email order items and customize them according to your choice. The files you need to override and change is here: `woocommerce/templates/emails/email-order-details.php` and `woocommerce/templates/emails/email-order-items.php`

Remember that you need to override this templates into your theme.

Let me know if you need further assistance.
