### ISSUE TITLE
CRITICAL Cannot redeclare woo_custom_emails_output_message()

### ISSUE THREAD

**Issue by e-DigitalDesign** [wp3sixty/woo-custom-emails#21]
CRITICAL Cannot redeclare woo_custom_emails_output_message() (previously declared in /wp-content/plugins/woo-custom-emails-per-product/includes/class-woo-custom-emails-output.php:50)

**Comment by mehulkaklotar** [comment]
@e-DigitalDesign As you can see this is not our plugin's issue. `woo-custom-emails-per-product` see this plugin. we don't have this function declared anywhere in the plugin.
