### ISSUE TITLE
Not working since WooCommerce 3.2

### ISSUE THREAD

**Issue by TomasHurtz** [wp3sixty/woo-custom-emails#22]
Hello devs

Are there plans to update this wonderful plugin?  It's not currently working for me - but was working fine before 3.2.

I use it to send failed subscription renewal notices - something I can't do currently.

Please let us know what options we have for keeping this alive?

Thanks for your great work.

**Comment by mehulkaklotar** [comment]
@TomasHurtz I have pushed new plugin upgrade. Please let me know if it works for you. I can fix issues if anything is there.

**Comment by TomasHurtz** [comment]
Great - it seems stable, thank you :-) :-)
