### ISSUE TITLE
Variable names are printed in the emal ({order_date}, {order_number},..), not their values

### ISSUE THREAD

**Issue by mihneabogdan** [wp3sixty/woo-custom-emails#26]
Hi,
WP 4.9.4
WC 3.1.2
All variable names are printed in the email body, cannot get their values. Snapshots below. What could we do about it?

![custom](https://user-images.githubusercontent.com/26408052/37979554-88d76398-31f1-11e8-87c9-ddf3190c2c3d.png)

![template](https://user-images.githubusercontent.com/26408052/37979677-dbfd11c6-31f1-11e8-9bde-381978877b1c.png)

**Comment by faishal** [comment]
@mihneabogdan This has been released in 2.2 ( resolved in #30 )
